name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'bugfix/**'

jobs:
  test:
    name: Run Jest Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  build-and-push-docker:
    name: Build and Push Docker Image
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t your-dockerhub-username/portfolio:latest .
          docker tag your-dockerhub-username/portfolio:latest your-dockerhub-username/portfolio:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push your-dockerhub-username/portfolio:latest
          docker push your-dockerhub-username/portfolio:${{ github.sha }}

